server:
  # 必须使用8160,后面的微信登录 wx授权回调域学校配置的是localhost:8160 使用别的端口将来不能测试
  port: 8887
spring:
  # 应用名称
  application:
    name: system-service
  # 数据库的相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql:///account_book?serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://${REMOTE_HOST:localhost}:32768/account_book?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://39.100.105.236:32768/account_book?serverTimezone=Asia/Shanghai
#    username: ${REMOTE_MYSQL_USERNAME:root}
    username: ENC(+UqVvXNR//wSI0Qp1xAh/PLrJKYjgnhAoyL5BAvngMvInTuxcijGEkaqtjjfUN8d)
#    password: ${REMOTE_MYSQL_PASSWORD:root}
    password: ENC(vqUawoWuP0ai73FSET+uU4hQN8gELwUediXJ41S86h2zc6G09JV8VqkwdE/89tn0Ntt3uu8kjao8dfuFf4qtHg==)
#    type: com.zaxxer.hikari.HikariDataSource
  # 配置文件的切换配置
  profiles:
    active: dev
  # 设置时间日期格式和时区的设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 39.100.105.236
#    host: ${REMOTE_HOST}
    port: 6379
    password: ENC(XC2ObTM80vSAsUNA5uTAjMp4OEg09wYpXsVXJS1xm62fZN3dcdocryBJpa6qbMTm)
#    password: ${REMOTE_REDIS_PASSWORD}
mybatis-plus:
  type-aliases-package: com.atguigu.accounting.entity
  configuration:
    # 启用sql语句的日志输入功能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 自定义mapper.xml文件的放置的路径
  mapper-locations: classpath*:/mapper/xml/*.xml
  # 主键id雪花算法生成全局配置
  global-config:
    db-config:
      id-type: assign_id

jasypt:
  encryptor:
    password: ${JASYPT_PASS}